{
 "title": "Couchbase",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pod", "label": "pod", "query": "label_values(cpu_rate, pod)" },
   { "name": "namespace", "label": "namespace", "query": "label_values(namespace)" },
   { "name": "bucket", "label": "bucket", "query": "label_values(bucket)" },
   { "name": "node", "label": "node", "query": "label_values(node)" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_cpu_utilization_rate{pod=~\"$pod\", bucket=~\"$bucket\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_mem_used_bytes{pod=~\"$pod\", bucket=~\"$bucket\", namespace=~\"$namespace\"}"
    },
    {
     "expr": "cbbucketstat_mem_actual_used_bytes{pod=~\"$pod\", bucket=~\"$bucket\", namespace=~\"$namespace\"}"
    },
    {
     "expr": "cbbucketstat_mem_actual_used_free{pod=~\"$pod\", bucket=~\"$bucket\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cbpernodebucket_curr_connections{pod=~\"$pod\", bucket=~\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Ops Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_ops{pod=~\"$pod\", bucket=~\"$bucket\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Gets Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_cmd_get{pod=~\"$pod\", bucket=~\"$bucket\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Sets Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_cmd_set{pod=~\"$pod\", bucket=~\"$bucket\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Items",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cbpernodebucket_curr_items{pod=~\"$pod\", bucket=~\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Disk Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_disk_write_queue{pod=~\"$pod\", bucket=~\"$bucket\", namespace=~\"$namespace\"}"
    },
    {
     "expr": "cbbucketstat_ep_diskqueue_items{pod=~\"$pod\", bucket=~\"$bucket\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Total Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_couch_total_disk_size{pod=~\"$pod\", bucket=~\"$bucket\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "vBucket Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_vbuckets_active_queue_size{pod=~\"$pod\", bucket=~\"$bucket\", namespace=~\"$namespace\", node=~\"$node\"}"
    },
    {
     "expr": "cbpernodebucket_vb_pending_queue_size{pod=~\"$pod\", node=~\"$node\", bucket=~\"$bucket\"}"
    },
    {
     "expr": "cbpernodebucket_vb_replica_queue_size{pod=~\"$pod\", bucket=~\"$bucket\", namespace=~\"$namespace\", node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Items Total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cbpernodebucket_curr_items_tot{pod=~\"$pod\", bucket=~\"$bucket\"}"
    }
   ]
  }
 ]
}